/**
 * Project Layer - Type Definitions
 *
 * Pure TypeScript interfaces for shader projects.
 * No implementation, no dependencies, just data structures.
 */

/**
 * Root data structure describing an entire shader project.
 */
export interface ProjectDefinition {
  /**
   * Project metadata (title is required)
   */
  meta: {
    title: string
    description?: string
    author?: string
    tags?: string[]
  }

  /**
   * Shared GLSL code prepended to all shaders.
   * Available in all passes.
   * Optional - many projects won't need shared code.
   */
  common?: string

  /**
   * Render target buffers.
   * Keys are buffer names (must be valid GLSL identifiers with 'u' prefix).
   * Can be empty object {} if only rendering to screen.
   */
  buffers: Record<string, BufferConfig>

  /**
   * External image textures.
   * Keys are texture names (must be valid GLSL identifiers with 'u' prefix).
   * Optional - many projects won't need external textures.
   */
  textures?: Record<string, TextureConfig>

  /**
   * Shader passes executed in array order.
   * Each pass runs a fragment shader, writing to a buffer or screen.
   * At least one pass is required.
   */
  passes: PassDefinition[]

  /**
   * User-controllable parameters.
   * Keys are parameter names (must be valid GLSL identifiers with 'u' prefix).
   * Optional - some projects have no user controls.
   */
  params?: Record<string, ParamConfig>

  /**
   * Named parameter presets (saved parameter configurations).
   * Keys are preset names (can be any string).
   * Values are parameter snapshots.
   * Optional - not all projects need presets.
   */
  presets?: Record<string, ParamValues>
}

/**
 * Configuration for a render target buffer.
 */
export interface BufferConfig {
  /**
   * Internal texture format.
   * - rgba8: Standard 8-bit color (0-255 per channel)
   * - rgba16f: Half-precision float (HDR, compute)
   * - rgba32f: Full-precision float (high-accuracy compute)
   */
  format: 'rgba8' | 'rgba16f' | 'rgba32f'

  /**
   * Buffer resolution behavior.
   * - 'inherit': Match canvas resolution (resizes with canvas)
   * - [width, height]: Fixed pixel size (e.g., [512, 512] for PDE grids)
   * - { width, aspectRatio }: Fixed width, height computed from aspect ratio
   * - { height, aspectRatio }: Fixed height, width computed from aspect ratio
   */
  resolution:
    | 'inherit'
    | [number, number]
    | { width: number; aspectRatio: number }
    | { height: number; aspectRatio: number }

  /**
   * Enable ping-pong buffering for temporal self-reference.
   * When true, Engine maintains prev/curr texture pair.
   * Pass reads from prev, writes to curr, then swaps immediately after write.
   */
  pingPong: boolean

  /**
   * Texture sampling filter mode.
   * - 'nearest': Pixel-exact sampling (no interpolation)
   * - 'linear': Bilinear interpolation (smooth)
   */
  filter: 'nearest' | 'linear'

  /**
   * Texture wrapping mode at edges.
   * - 'clamp': Clamp to edge (repeat edge pixels)
   * - 'repeat': Tile texture (wrap around)
   */
  wrap: 'clamp' | 'repeat'

  /**
   * Initial clear color [r, g, b, a] in range [0, 1].
   * Applied once at buffer creation if no init shader provided.
   */
  clear: [number, number, number, number]

  /**
   * Optional initialization shader.
   * GLSL fragment shader code that runs once to set initial buffer state.
   * If provided, this is used instead of clear color.
   * Has access to all uniforms (uResolution, uTime, etc.) and can create
   * patterns, noise, or custom initial conditions.
   */
  init?: string
}

/**
 * Configuration for external image textures.
 */
export interface TextureConfig {
  /**
   * Path to image file (PNG/JPG).
   * Relative to project root or absolute URL.
   * Loaded as rgba8 format.
   */
  source: string

  /**
   * Texture sampling filter mode.
   * - 'nearest': Pixel-exact sampling
   * - 'linear': Bilinear interpolation
   */
  filter: 'nearest' | 'linear'

  /**
   * Texture wrapping mode at edges.
   * - 'clamp': Clamp to edge
   * - 'repeat': Tile texture
   */
  wrap: 'clamp' | 'repeat'
}

/**
 * A single shader pass in the rendering pipeline.
 */
export interface PassDefinition {
  /**
   * Unique pass identifier.
   * Used for debugging, error messages, and selective recompilation.
   */
  name: string

  /**
   * Original shader source (what the author wrote).
   * Clean GLSL fragment shader code.
   * Displayed in code editors.
   * Contains main() function with logic.
   * Should use 'fragColor' as output variable (declared by compiler).
   */
  source: string

  /**
   * Compiled shader source (generated by compiler).
   * Includes version directive, precision, uniforms, common code, and source.
   * Used by Engine for WebGL compilation.
   * Optional - only present after compileProject() is called.
   * Contains complete fragment shader program.
   */
  shader?: string

  /**
   * Output target for this pass.
   * Either a buffer name (key from project.buffers) or 'screen' for canvas.
   */
  output: string
}

/**
 * Float parameter with min/max/step configuration.
 */
export interface FloatParam {
  type: 'float'

  /**
   * Default value (initial parameter state)
   */
  default: number

  /**
   * Minimum value for UI slider
   */
  min: number

  /**
   * Maximum value for UI slider
   */
  max: number

  /**
   * Slider step size (granularity).
   * Optional - defaults to (max - min) / 100
   */
  step?: number

  /**
   * Human-readable label for UI.
   * Optional - defaults to parameter name
   */
  label?: string
}

/**
 * Boolean parameter (checkbox).
 */
export interface BoolParam {
  type: 'bool'

  /**
   * Default value (initial parameter state)
   */
  default: boolean

  /**
   * Human-readable label for UI.
   * Optional - defaults to parameter name
   */
  label?: string
}

/**
 * Integer parameter with min/max configuration.
 * Useful for algorithm selection, iteration counts, etc.
 */
export interface IntParam {
  type: 'int'

  /**
   * Default value (initial parameter state)
   */
  default: number

  /**
   * Minimum value
   */
  min: number

  /**
   * Maximum value
   */
  max: number

  /**
   * Human-readable label for UI.
   * Optional - defaults to parameter name
   */
  label?: string
}

/**
 * Vec3 parameter (color picker).
 * RGB color in range [0, 1] for each component.
 */
export interface Vec3Param {
  type: 'vec3'

  /**
   * Default value [r, g, b] in range [0, 1]
   */
  default: [number, number, number]

  /**
   * Human-readable label for UI.
   * Optional - defaults to parameter name
   */
  label?: string
}

/**
 * Union type for all parameter configurations.
 */
export type ParamConfig = FloatParam | BoolParam | IntParam | Vec3Param

/**
 * Type for parameter value snapshots (used in presets and runtime state).
 */
export type ParamValues = Record<string, number | boolean | [number, number, number]>
